/**
 * A machine-readable format for specifying errors in HTTP API responses
 * based on [RFC 7807](https://tools.ietf.org/html/rfc7807).
 */
export interface ProblemDetails {
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail: string | null;

  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance: string | null;

  /**
   * The HTTP status code generated by the origin server for this occurrence
   * of the problem.
   */
  status: number | null;

  /** A short, human-readable summary of the problem type. */
  title: string | null;

  /** A URI reference that identifies the problem type. */
  type: string | null;
}
